# Naver API
NAVER_CLIENT_ID = "your_client_id"
NAVER_CLIENT_SECRET = "your_client_secret"

# OpenAI API
OPENAI_API_KEY = "your_openai_key"

# Notion (선택사항)
NOTION_TOKEN = "your_notion_token"
NOTION_DATABASE_ID = "your_notion_database_id" 